# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@language = TechnologyType.create(name:"language")
TechnologyProperty.create(display_name:"primary use", property_type:"text", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"supported paradigms", property_type:"text", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"compiler type", property_type:"text", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"type system", property_type:"text", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"memory management", property_type:"text", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"concurrency support", property_type:"text", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"supports pass by reference", property_type:"boolean", technology_type_id:@language.id)
TechnologyProperty.create(display_name:"supports pass by value", property_type:"boolean", technology_type_id:@language.id)

@framework = TechnologyType.create(name:"Web Framework")
TechnologyProperty.create(display_name:"Language", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"ORM", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Paradigm", property_type:"text", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Internationalization", property_type:"boolean", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Localization", property_type:"boolean", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Testing Framework", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"DB Migration Framework", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Security Framework", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Template Framework", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Caching Framework", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Build Tool", property_type:"technology", technology_type_id:@framework.id)
TechnologyProperty.create(display_name:"Dependency Manager", property_type:"technology", technology_type_id:@framework.id)

@build = TechnologyType.create(name:"Build Tool")
TechnologyProperty.create(display_name:"Built on language", property_type:"technology", technology_type_id:@build.id)
TechnologyProperty.create(display_name:"Specification language", property_type:"technology", technology_type_id:@build.id)

@dependencies = TechnologyType.create(name:"Dependency Manager")
TechnologyProperty.create(display_name:"Language or framework", property_type:"technology", technology_type_id:@dependencies.id)
TechnologyProperty.create(display_name:"Specification language", property_type:"technology", technology_type_id:@dependencies.id)

@ci = TechnologyType.create(name:"Continuous Integration Tool")
TechnologyProperty.create(display_name:"Build tools", property_type:"technology", technology_type_id:@ci.id)
TechnologyProperty.create(display_name:"Version control", property_type:"technology", technology_type_id:@ci.id)
TechnologyProperty.create(display_name:"Notification", property_type:"text", technology_type_id:@ci.id)
TechnologyProperty.create(display_name:"Integrates with", property_type:"technology", technology_type_id:@ci.id)

@job = TechnologyType.create(name:"Job Scheduler")
TechnologyProperty.create(display_name:"user interface", property_type:"text", technology_type_id:@job.id)
TechnologyProperty.create(display_name:"data storage", property_type:"text", technology_type_id:@job.id)
TechnologyProperty.create(display_name:"OS", property_type:"technology", technology_type_id:@job.id)

@package = TechnologyType.create(name:"Package Manager")
TechnologyProperty.create(display_name:"OS", property_type:"technology", technology_type_id:@package.id)

@orm = TechnologyType.create(name:"ORM")
TechnologyProperty.create(display_name:"Language or framework", property_type:"technology", technology_type_id:@orm.id)
TechnologyProperty.create(display_name:"Databases", property_type:"technology", technology_type_id:@orm.id)

@test = TechnologyType.create(name:"Testing Framework")
TechnologyProperty.create(display_name:"Language or framework", property_type:"technology", technology_type_id:@test.id)

@security = TechnologyType.create(name:"Security Framework")
TechnologyProperty.create(display_name:"Language or framework", property_type:"technology", technology_type_id:@security.id)

@template = TechnologyType.create(name:"Template Framework")
TechnologyProperty.create(display_name:"Language or framework", property_type:"technology", technology_type_id:@template.id)

@cache = TechnologyType.create(name:"Caching Framework")
TechnologyProperty.create(display_name:"Language or framework", property_type:"technology", technology_type_id:@cache.id)

@frontend = TechnologyType.create(name:"Front-end Framework")
TechnologyProperty.create(display_name:"Browser support", property_type:"browser", technology_type_id:@frontend.id)
TechnologyProperty.create(display_name:"Size", property_type:"text", technology_type_id:@frontend.id)
TechnologyProperty.create(display_name:"Feature Detection", property_type:"text", technology_type_id:@frontend.id)
TechnologyProperty.create(display_name:"Paradigm", property_type:"text", technology_type_id:@frontend.id)

@ide = TechnologyType.create(name:"IDE")
TechnologyProperty.create(display_name:"Languages", property_type:"technology", technology_type_id:@ide.id)
TechnologyProperty.create(display_name:"Frameworks", property_type:"technology", technology_type_id:@ide.id)
TechnologyProperty.create(display_name:"Version controls", property_type:"technology", technology_type_id:@ide.id)

@di = TechnologyType.create(name:"Dependency Injection Framework")
TechnologyProperty.create(display_name:"Language", property_type:"technology", technology_type_id:@di.id)
TechnologyProperty.create(display_name:"Specification language", property_type:"technology", technology_type_id:@di.id)

@etl = TechnologyType.create(name:"ETL Tool")
TechnologyProperty.create(display_name:"Databases", property_type:"technology", technology_type_id:@etl.id)
TechnologyProperty.create(display_name:"Language", property_type:"technology", technology_type_id:@etl.id)

@database = TechnologyType.create(name:"Database")
TechnologyProperty.create(display_name:"OS", property_type:"technology", technology_type_id:@database.id)
TechnologyProperty.create(display_name:"ACID", property_type:"boolean", technology_type_id:@database.id)
TechnologyProperty.create(display_name:"Referential Integrity", property_type:"boolean", technology_type_id:@database.id)
TechnologyProperty.create(display_name:"Transactions", property_type:"boolean", technology_type_id:@database.id)
TechnologyProperty.create(display_name:"Unicode support", property_type:"boolean", technology_type_id:@database.id)
TechnologyProperty.create(display_name:"type", property_type:"text", technology_type_id:@database.id)

@os = TechnologyType.create(name:"Operating System")
TechnologyProperty.create(display_name:"Package Managers", property_type:"technology", technology_type_id:@os.id)
TechnologyProperty.create(display_name:"Resource access control", property_type:"text", technology_type_id:@os.id)
TechnologyProperty.create(display_name:"Subsystem isolation mechanism", property_type:"text", technology_type_id:@os.id)
TechnologyProperty.create(display_name:"Integrated firewall", property_type:"boolean", technology_type_id:@os.id)
TechnologyProperty.create(display_name:"Filesystems supported", property_type:"technology", technology_type_id:@os.id)

@fs = TechnologyType.create(name:"Filesystem")
TechnologyProperty.create(display_name:"OSes", property_type:"technology", technology_type_id:@fs.id)
TechnologyProperty.create(display_name:"Hard links", property_type:"boolean", technology_type_id:@fs.id)
TechnologyProperty.create(display_name:"Symbolic links", property_type:"boolean", technology_type_id:@fs.id)
TechnologyProperty.create(display_name:"Block journaling", property_type:"boolean", technology_type_id:@fs.id)
TechnologyProperty.create(display_name:"Metadata-only journaling", property_type:"boolean", technology_type_id:@fs.id)

TechnologyType.create(name:"Virtual Machine")

@cloud = TechnologyType.create(name:"Cloud provider")
TechnologyProperty.create(display_name:"OSes supported", property_type:"technology", technology_type_id:@cloud.id)

@mapreduce = TechnologyType.create(name:"Map/Reduce implementation")
TechnologyProperty.create(display_name:"Languages", property_type:"technology", technology_type_id:@mapreduce.id)

@orch = TechnologyType.create(name:"IT orchestration framework")
TechnologyProperty.create(display_name:"Specification language", property_type:"technology", technology_type_id:@orch.id)

TechnologyType.create(name:"Code-hosting service")

@vcs = TechnologyType.create(name:"Version Control")
TechnologyProperty.create(display_name:"Respository model", property_type:"text", technology_type_id:@vcs.id)
TechnologyProperty.create(display_name:"Concurrency model", property_type:"text", technology_type_id:@vcs.id)
TechnologyProperty.create(display_name:"Storage method", property_type:"text", technology_type_id:@vcs.id)
TechnologyProperty.create(display_name:"Scope of change", property_type:"text", technology_type_id:@vcs.id)

@vcsgui = TechnologyType.create(name:"Version Control GUI")
TechnologyProperty.create(display_name:"Version Control", property_type:"technology", technology_type_id:@vcsgui.id)

@shell = TechnologyType.create(name:"Shell")
TechnologyProperty.create(display_name:"OS", property_type:"technology", technology_type_id:@shell.id)

TechnologyType.create(name:"Web server")

@dbs = TechnologyType.create(name:"Database management tool")
TechnologyProperty.create(display_name:"Databases supported", property_type:"technology", technology_type_id:@dbs.id)

TechnologyType.create(name:"Infrastructure Monitoring")

TechnologyType.create(name:"Realtime monitoring")

TechnologyType.create(name:"Business reporting tool")

TechnologyType.create(name:"Analytics tool")

TechnologyType.create(name:"Mail Server")

TechnologyType.create(name:"Mail Hosting Service")

TechnologyType.create(name:"CRM tool")

TechnologyType.create(name:"Cache")

@browser = TechnologyType.create(name:"Browser")
TechnologyProperty.create(display_name:"OS", property_type:"technology", technology_type_id:@browser.id)

@cms = TechnologyType.create(name:"CMS")

License.create(link:"http://www.gnu.org/licenses/gpl.html", name:"GNU General Public License (GPL) version 3")
License.create(link:"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html", name:"GNU General Public License (GPL) version 2")
License.create(link:"http://www.gnu.org/licenses/lgpl.html", name:"GNU Lesser General Public License (LGPL) version 3")
License.create(link:"http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html", name:"GNU Lesser General Public License (LGPL) version 2.1")
License.create(link:"http://www.gnu.org/licenses/agpl.html", name:"GNU Affero General Public License (AGPL) version 3")
License.create(link:"http://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html",
name:"GNU All-Permissive License")
License.create(link:"http://directory.fsf.org/wiki/License:Apache2.0", name:"Apache License, Version 2.0")
License.create(link:"http://directory.fsf.org/wiki/License:ArtisticLicense2.0", name:"Artistic License 2.0")
License.create(link:"http://gianluca.dellavedova.org/2011/01/03/clarified-artistic-license/",
name:"Clarified Artistic License</dt>")
License.create(link:"http://directory.fsf.org/wiki/License:Sleepycat", name:"Berkeley Database License")
License.create(link:"http://directory.fsf.org/wiki/License:Boost1.0", name:"Boost Software License")
License.create(link:"http://directory.fsf.org/wiki/License:BSD_3Clause", name:"Modified BSD license")
License.create(link:"http://directory.fsf.org/wiki/License:CC0", name:"CC0")
License.create(link:"http://www.cecill.info/licences.en.html", name:"CeCILL version 2")
License.create(link:"http://directory.fsf.org/wiki/License:ClearBSD",
   name:"The Clear BSD License")
License.create(link:"http://directory.fsf.org/wiki/License:CryptixGL", name:"Cryptix General License")
License.create(link:"http://directory.fsf.org/wiki/License:LaTeX_ecfonts", name:"License of the ec fonts for LaTeX")
License.create(link:"http://directory.fsf.org/wiki/License:ECos2.0", name:"eCos license version License.create(2.0)")
License.create(link:"http://directory.fsf.org/wiki/License:ECL2.0", name:"Educational Community License 2.0")
License.create(link:"http://directory.fsf.org/wiki/License:EFLv2", name:"Eiffel Forum License, version 2")
License.create(link:"http://directory.fsf.org/wiki/License:EUDataGrid", name:"EU DataGrid Software License")
License.create(link:"http://directory.fsf.org/wiki/License:Expat", name:"Expat License")
License.create(link:"http://directory.fsf.org/wiki?title=License:FreeBSD", name:"FreeBSD license")
License.create(link:"http://directory.fsf.org/wiki/License:FreeType", name:"Freetype Project License")
License.create(link:"http://directory.fsf.org/wiki?title=License:SFL",name:"License of the iMatix Standard Function Library")
License.create(link:"http://directory.fsf.org/wiki?title=License:JPEG", name:"Independent JPEG Group License")
License.create(link:"http://directory.fsf.org/wiki/License:Imlib2", name:"License of imlib2")
License.create(link:"http://directory.fsf.org/wiki/License:IntelACPI", name:"Intel Open Source License")
License.create(link:"http://directory.fsf.org/wiki/License:ISC", name:"ISC License")
License.create(link:"http://directory.fsf.org/wiki/License:MPLv2.0",name:"Mozilla
Public License (MPL) version 2.0")
License.create(link:"http://directory.fsf.org/wiki/License:IllinoisNCSA", name:"NCSA/University of Illinois Open Source License")
License.create(    name:"License of Netscape JavaScript")
License.create(link:"http://directory.fsf.org/wiki/License:OpenLDAPv2.7", name:"OpenLDAP License, Version 2.7")
License.create(name:"License of Perl 5 and below")
License.create(link:"http://directory.fsf.org/wiki/License:PublicDomain", name:"Public Domain")
License.create(link:"http://directory.fsf.org/wiki?title=License:Python2.0.1", name:"License of Python 2.0.1, 2.1.1, and newer versions")
License.create(link:"http://directory.fsf.org/wiki?title=License:Python1.6a2", name:"License of Python 1.6a2 and earlier versions")
License.create(link:"http://directory.fsf.org/wiki/License:Ruby", name:"License of Ruby")
License.create(link:"http://directory.fsf.org/wiki/License:SGIFreeBv2", name:"SGI Free Software License B, version 2.0")
License.create(link:"http://directory.fsf.org/wiki/License:StandardMLofNJ", name:"Standard ML of New Jersey Copyright License")
License.create(link:"http://directory.fsf.org/wiki/License:Unicode", name:"Unicode, Inc. License Agreement for Data Files and Software")
License.create(link:"http://directory.fsf.org/wiki/License:TheUnlicense", name:"The Unlicense")
License.create(link:"http://directory.fsf.org/wiki/License:Vim7.2", name:"License of Vim, Version 6.1 or later")
License.create(link:"http://directory.fsf.org/wiki/License:W3C_31Dec2002", name:"W3C Software Notice and License")
License.create(link:"http://directory.fsf.org/wiki/License:WebM", name:"License of WebM")
License.create(link:"http://sam.zoy.org/wtfpl/COPYING", name:"WTFPL, Version 2")
License.create(link:"http://directory.fsf.org/wiki/License:X11", name:"X11 License")
License.create(link:"http://directory.fsf.org/wiki/License:XFree86_1.1",name:"XFree86 1.1 License")
License.create(link:"http://directory.fsf.org/wiki/License:Zlib", name:"License of ZLib")
License.create(link:"http://directory.fsf.org/wiki?title=License:ZopePLv2.1", name:"Zope Public License.create(License, versions 2.0 and 2.1")
License.create(name:"WxWidgets License")
License.create(link:"http://directory.fsf.org/wiki/License:AGPLv1", name:"Affero General Public License version 1")
License.create(link:"http://directory.fsf.org/wiki/License:AFLv3", name:"Academic Free License, all versions through 3.0")
License.create(link:"http://directory.fsf.org/wiki/License:Apache1.1", name:"Apache License, Version 1.1")
License.create(link:"http://directory.fsf.org/wiki/License:Apache1.0", name:"Apache License, Version 1.0")
License.create(link:"http://directory.fsf.org/wiki/License:APSLv2.0", name:"Apple Public Source License (APSL), version 2")
License.create(link:"http://directory.fsf.org/wiki/License:BitTorrentOSL1.1", name:"BitTorrent Open Source License")
License.create(link:"http://directory.fsf.org/wiki/License:BSD_4Clause", name:"Original BSD license")
License.create(link:"http://directory.fsf.org/wiki/License:CDDLv1.0", name:"Common Development and Distribution License (CDDL), version 1.0")
License.create(link:"https://www.socialtext.net/open/cpal_license_in_wikitext", name:"Common Public Attribution License 1.0 (CPAL)")
License.create(link:"http://directory.fsf.org/wiki/License:CPLv1.0", name:"Common Public License Version 1.0")
License.create(link:"http://directory.fsf.org/wiki?title=License:Condor1.1", name:"Condor Public License")
License.create(link:"http://directory.fsf.org/wiki/License:EPLv1.0", name:"Eclipse Public License Version 1.0")
License.create(link:"http://directory.fsf.org/wiki/License:EUPLv1.1", name:"European Union Public License (EUPL) version 1.1")
License.create(link:"http://directory.fsf.org/wiki/License:IBMPLv1.0", name:"IBM Public License, Version 1.0")
License.create(link:"http://directory.fsf.org/wiki/License:JabberOSLv1.0", name:"Jabber Open Source License, Version 1.0")
License.create(link:"http://directory.fsf.org/wiki/License:LPPLv1.3a", name:"LaTeX Project Public License 1.3a")
License.create(link:"http://directory.fsf.org/wiki/License:LPPLv1.2", name:"LaTeX Project Public License 1.2")
License.create(link:"http://directory.fsf.org/wiki/License:LucentPLv1.02", name:"Lucent Public License Version 1.02 (Plan 9 license)")
License.create(link:"http://directory.fsf.org/wiki/License:MsPL", name:"Microsoft Public License (Ms-PL)")
License.create(link:"http://directory.fsf.org/wiki/License:MsRL", name:"Microsoft Reciprocal License (Ms-RL)")
License.create(link:"http://directory.fsf.org/wiki/License:MPLv1.1", name:"Mozilla Public License (MPL) version 1.1")
License.create(link:"http://directory.fsf.org/wiki/License:NOSLv1.0", name:"Netizen Open Source License (NOSL), Version 1.0")
License.create(link:"http://directory.fsf.org/wiki?title=License:NPLv1.1", name:"Netscape Public License (NPL), versions 1.0 and 1.1")
License.create(link:"http://directory.fsf.org/wiki/License:NokOSv1.0a", name:"Nokia Open Source License")
License.create(link:"http://directory.fsf.org/wiki/License:OpenLDAPv2.3", name:"Old OpenLDAP License, Version 2.3")
License.create(link:"http://directory.fsf.org/wiki/License:OSLv3.0", name:"Open Software License, all versions through 3.0")
License.create(link:"http://directory.fsf.org/wiki/License:OpenSSL", name:"OpenSSL license")
License.create(link:"http://directory.fsf.org/wiki/License:Phorum2.0", name:"Phorum License, Version 2.0")
License.create(link:"http://directory.fsf.org/wiki/License:PHPv3.01", name:"PHP License, Version 3.01")
License.create(link:"http://directory.fsf.org/wiki/License:Python1.6b1", name:"License of Python 1.6b1 through 2.0 and 2.1")
License.create(link:"http://directory.fsf.org/wiki/License:QPLv1.0", name:"Q Public License (QPL), Version 1.0")
License.create(link:"http://directory.fsf.org/wiki/License:RPSLv1.0", name:"RealNetworks Public Source License (RPSL), Version 1.0")
License.create(link:"http://www.openoffice.org/licenses/sissl_license.html", name:"Sun Industry Standards Source License 1.0")
License.create(link:"http://directory.fsf.org/wiki/License:SPLv1.0", name:"Sun Public License")
License.create(link:"http://directory.fsf.org/wiki/License:Xinetd", name:"License of xinetd")
License.create(link:"http://www.zimbra.com/license/yahoo_public_license_1.1.html", name:"Yahoo! Public License 1.1")
License.create(link:"http://www.zend.com/license/2_00.txt", name:"Zend License, Version 2.0")
License.create(link:"http://www.zimbra.com/license/zimbra-public-license-1-3.html", name:"Zimbra Public License 1.3")
License.create(link:"http://web.archive.org/web/20000816090640/http://www.zope.org/Resources/ZPL",
name:"Zope Public License version 1")
License.create( name:"No license")
License.create(name:"Aladdin Free Public License")
License.create(link:"http://directory.fsf.org/wiki/License:APSLv1.x", name:"Apple Public Source License (APSL), version 1.x")
License.create(name:"Artistic License 1.0")
License.create(name:"AT&amp;T Public License")
License.create(name:"Code Project Open License, version 1.02")
License.create(name:"eCos Public License, version 1.1")
License.create(link:"http://directory.fsf.org/wiki/License:GPL-PA", name:"GPL for Computer Programs of the Public Administration")
License.create(link:"http://www.hacktivismo.com/about/hessla.php", name:"Hacktivismo Enhanced-Source Software License Agreement (HESSLA)")
License.create(link:"http://web.archive.org/web/20050317081359/http://www.jahia.org/jahia/page145.html",name:"Jahia Community Source License")
License.create(link:"http://directory.fsf.org/wiki/License:JSON",name:"The JSON License")
License.create(name:"Old license of ksh93")
License.create(link:"http://directory.fsf.org/wiki/License:Lha", name:"License of Lha")
License.create(link:"http://directory.fsf.org/wiki/License:Ms-SS", name:"Microsoft's Shared Source CLI, C#, and Jscript License")
License.create(link:"http://directory.fsf.org/wiki/License:NASA-OSA_v1.3", name:"NASA Open Source Agreement")
License.create(link:"http://directory.fsf.org/wiki/License:OpenPLv1.0", name:"Open Public License")
License.create(link:"http://directory.fsf.org/wiki/License:PINE", name:"License of PINE")
License.create(name:"Old Plan 9 license")
License.create(link:"http://directory.fsf.org/wiki/License:ReciprocalPLv1.3",name:"Reciprocal Public License")
License.create(name:"Public License")
License.create(link:"http://directory.fsf.org/wiki/License:SimpleM", name:"Simple Machines License")
License.create(link:"http://directory.fsf.org/wiki/License:Squeak-old", name:"Old
Squeak license")
License.create(link:"http://directory.fsf.org/wiki/License:SunCSLv2.8", name:"Sun
Community Source License")
License.create(link:"http://www.openwatcom.org/index.php/Open_Watcom_Public_License", name:"Sybase Open Watcom Public License version 1.0")
License.create(link:"http://www.accellera.org/about/policies/SystemC_Open_Source_License.pdf",
name:"SystemC “Open Source” License, Version 3.0")
License.create(link:"http://www.cs.utah.edu/~gk/teem/txt/LICENSE.txt", name:"University of Utah Public License")
License.create(name:"YaST License")
License.create(link:"http://www.gnu.org/licenses/fdl.html", name:"GNU Free Documentation License")
License.create(link:"http://fedoraproject.org/wiki/Licensing/Common_Documentation_License",
name:"Apple's Common Documentation License, Version 1.0")
License.create(link:"http://directory.fsf.org/wiki?title=License:FreeBSD", name:"FreeBSD Documentation License")
License.create(link:"http://opencontent.org/openpub/", name:"Open Publication License, Version 1.0")
License.create(link:"http://opencontent.org/opl.shtml", name:"Open Content License, Version 1.0")
License.create(link:"http://www.gnu.org/licenses/gpl.html", name:"GNU General Public License")
License.create(link:"http://www.gnu.org/licenses/fdl.html", name:"GNU Free Documentation License")
License.create(link:"http://creativecommons.org/licenses/by/2.0/legalcode", name:"Creative Commons Attribution 2.0 license (a.k.a. CC&nbsp;BY)")
License.create(link:"http://creativecommons.org/licenses/by-sa/2.0/legalcode", name:"Creative Commons Attribution-Sharealike 2.0 license (a.k.a. CC&nbsp;BY-SA)")
License.create(link:"http://www.gnu.org/licenses/dsl.html", name:"Design Science License (DSL)")
License.create(link:"http://artlibre.org/licence/lal/en", name:"Free Art License")
License.create(link:"http://directory.fsf.org/wiki/License:ODbl", name:"Open Database license")
License.create(link:"http://www.gnu.org/licenses/gpl.html", name:"GNU General Public License")
License.create(link:"http://ftp.gnu.org/gnu/non-gnu/chinese-fonts-truetype/LICENSE", name:"Arphic Public License")
License.create(link:"http://scripts.sil.org/OFL_web", name:"SIL Open Font License 1.1")
License.create(link:"http://www.gnu.org/licenses/licenses.html#VerbatimCopying", name:"GNU Verbatim Copying License")
License.create(link:"http://creativecommons.org/licenses/by-nd/3.0/legalcode", name:"Creative Commons Attribution-NoDerivs 3.0 license (a.k.a. CC&nbsp;BY-ND)")


